name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ libgtest-dev cmake

    - name: Build
      run: |
        sudo apt-get install -y cmake
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        GTEST_COLOR=1 GTEST_OUTPUT=xml:test_detail.xml GTEST_FILTER=* make test

    - name: Archive the build
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test_detail.xml
